### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by 1UC1F3R616** [1UC1F3R616/fastProxy#1]
- Web Scrape code seems to be broken with time. Update needed.

**Comment by searchformyusername** [comment]
I have got some  free time, on the task! Will do a complete revamp.

**Comment by searchformyusername** [comment]
https://pypi.org/project/fastProxy/1.0.0/

Release done, project is functional now and also supports proxy from one new source.

Will be adding one more source sooner and more fixes+features to come.
